# Video output
vo=gpu-next
gpu-api=vulkan           # Try 'opengl' if Vulkan causes issues
profile=high-quality           # High-quality rendering preset

# Hardware decoding
hwdec=vaapi          # Use VAAPI on Intel iGPU safely
hwdec-codecs=all

# Display sync & frame timing
video-sync=display-resample
interpolation=no
tscale=oversample        # Better frame timing (smoother motion)

glsl-shaders="/usr/share/anime4k/Restore/Anime4K_Restore_CNN_M.glsl;/usr/share/anime4k/Upscale/Anime4K_Upscale_CNN_x2_M.glsl"


# Scaling (HQ but efficient)
scale=bilinear
cscale=bilinear

# Subtitles
sub-auto=fuzzy
sub-pos=100
sub-font="JetBrainsMono Nerd"
sub-font-size=25
sub-border-size=1.5
sub-color="#FFFFFF"
sub-shadow-color="#000000"
sub-shadow-offset=1

# Audio
volume=100
audio-channels=stereo

# Misc
keep-open=yes
ytdl-format=bestvideo[ext=mp4]+bestaudio[ext=m4a]/best
save-position-on-quit

# Screenshots
screenshot-directory=~/Pictures/screenshots
screenshot-format=png
